- name: setup for mysql rpi nodes 
  hosts: mysqldb
  remote_user: pi
  become: yes

  tasks:

  - name: Install mariaDB Server
    apt: 
      name: mariadb-server 
      state: present

  - name: Install mariaDB Client
    apt: 
      name: mariadb-client 
      state: present
  
  - name: Start the MariaDB service
    action: service name=mariadb state=started

  - name: Install PyMySQL python package
    pip:
      name: PyMySQL
  
  - name: Ensure mysqld is listening to all ip
    ini_file:
      path: /etc/mysql/my.cnf
      section: mysqld
      option: bind-address
      value: 0.0.0.0
      backup: yes
    register: service_conf
  
  - name: restart mysqld
    service:
      name: mysqld
      state: restarted
    when: service_conf.changed